[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "ezwald"
version = "0.6.0"
authors = [
  { name="Emilia Szynwald", email="emiliaszynwald@gmail.com " },
]
description = "Evaluate electrostatic energy of multi-layer vand der Waals systems with geometry optimization capabilities."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/EmiliaSzynwald/EZwald"
Issues = "https://github.com/EmiliaSzynwald/EZwald/issues"
